const products = [
    {
        id: 1,
        title: "MacBook Pro",
        image: "../img/altavoces.jpg",
        description: "Procesador M1, 8 GB de RAM, 256 GB de almacenamiento",
        price: "$1,299.00",
      },
      {
        id: 2,
        title: "iPhone 13",
        image: "../img/altavoces.jpg",
        description: "Pantalla OLED de 6.1 pulgadas, chip A15 Bionic, 128 GB de almacenamiento",
        price: "$799.00",
      },
      {
        id: 3,
        title: "Samsung Galaxy S21 Ultra",
        image: "../img/altavoces.jpg",
        description: "Pantalla AMOLED de 6.8 pulgadas, procesador Exynos 2100, 12 GB de RAM, 256 GB de almacenamiento",
        price: "$1,199.00",
      },
      {
        id: 4,
        title: "iPad Pro",
        image: "../img/altavoces.jpg",
        description: "Pantalla Liquid Retina XDR de 12.9 pulgadas, chip M1, 128 GB de almacenamiento",
        price: "$1,099.00",
      },
      {
        id: 5,
        title: "Apple Watch Series 7",
        image: "../img/altavoces.jpg",
        description: "Pantalla Retina siempre activa, monitor de oxígeno en sangre, GPS, 44 mm",
        price: "$399.00",
      },
      {
        id: 6,
        title: "Sony WH-1000XM4",
        image: "../img/altavoces.jpg",
        description: "Auriculares inalámbricos con cancelación de ruido, hasta 30 horas de duración de la batería",
        price: "$349.99",
      },
      {
        id: 7,
        title: "Nvidia GeForce RTX 3080 Ti",
        image: "../img/altavoces.jpg",
        description: "Tarjeta gráfica para gaming de alto rendimiento, 12 GB de memoria GDDR6X",
        price: "$1,199.00",
      },
      {
        id: 8,
        title: "Samsung Odyssey G9",
        image: "../img/altavoces.jpg",
        description: "Monitor gaming curvo de 49 pulgadas, resolución de 5120 x 1440 píxeles, frecuencia de actualización de 240 Hz",
        price: "$1,499.99",
      },
      {
        id: 9,
        title: "DJI Mavic Air 2S",
        image: "../img/altavoces.jpg",
        description: "Dron con cámara de 20 MP, resolución de video de 5.4K, hasta 31 minutos de duración de la batería",
        price: "$999.00",
      },
      {
        id: 10,
        title: "Bicicleta",
        image: "../img/altavoces.jpg",
        description: "Bicicleta de montaña",
        price: 299.99,
      },
      {
        id: 11,
        title: "Laptop",
        image: "../img/altavoces.jpg",
        description: "Laptop de última generación",
        price: 1399.99,
      },
      {
        id: 12,
        title: "Smartphone",
        image: "../img/altavoces.jpg",
        description: "Smartphone con cámara de alta resolución",
        price: 799.99,
      },
      {
        id: 13,
        title: "TV",
        image: "../img/altavoces.jpg",
        description: "TV de pantalla plana",
        price: 499.99,
      },
      {
        id: 14,
        title: "Tablet",
        image: "../img/altavoces.jpg",
        description: "Tablet con pantalla de alta resolución",
        price: 399.99,
      },
      {
        id: 15,
        title: "Silla de oficina",
        image: "../img/altavoces.jpg",
        description: "Silla de oficina ergonómica",
        price: 199.99,
      },
      {
        id: 16,
        title: "Cámara",
        image: "../img/altavoces.jpg",
        description: "Cámara profesional",
        price: 899.99,
      },
      {
        id: 17,
        title: "Altavoces",
        image: "../img/altavoces.jpg",
        description: "Altavoces de alta calidad",
        price: 299.99,
      },
      {
        id: 18,
        title: "Reloj inteligente",
        image: "../img/altavoces.jpg",
        description: "Reloj inteligente con GPS",
        price: 149.99,
      },
      {
        id: 19,
        title: "Gafas de sol",
        image: "../img/altavoces.jpg",
        description: "Gafas de sol con protección UV",
        price: 49.99,
      },
      {
        id: 20,
        title: "Teclado",
        image: "../img/altavoces.jpg",
        description: "Teclado mecánico para gaming",
        price: 99.99,
      },
     
  ];
  
  export default products;


